#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.DoAn.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ThucTap_DoAn")]
	public partial class ThucTap_DoAnDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ThucTap_DoAnDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ThucTap_DoAnConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThucTap_DoAnDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThucTap_DoAnDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThucTap_DoAnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThucTap_DoAnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DanhSachQuanLyThu")]
		public ISingleResult<sp_DanhSachQuanLyThuResult> sp_DanhSachQuanLyThu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string ptrangthai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ptrangthai);
			return ((ISingleResult<sp_DanhSachQuanLyThuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeletePhieuThu")]
		public int sp_DeletePhieuThu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string soPhieu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soPhieu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ChiTietPhieuThu")]
		public ISingleResult<sp_ChiTietPhieuThuResult> sp_ChiTietPhieuThu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string soPhieu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soPhieu);
			return ((ISingleResult<sp_ChiTietPhieuThuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetSinhVien")]
		public ISingleResult<sp_GetSinhVienResult> sp_GetSinhVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string mssv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string matkhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mssv, matkhau);
			return ((ISingleResult<sp_GetSinhVienResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_DanhSachQuanLyThuResult
	{
		
		private string _SoPhieu;
		
		private string _mssv;
		
		private string _NoiDung;
		
		private System.Nullable<decimal> _SoTienThu;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private string _TrangThai;
		
		public sp_DanhSachQuanLyThuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="VarChar(10)")]
		public string mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					this._mssv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(100)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienThu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoTienThu
		{
			get
			{
				return this._SoTienThu;
			}
			set
			{
				if ((this._SoTienThu != value))
				{
					this._SoTienThu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this._NgayThanhToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(20)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class sp_ChiTietPhieuThuResult
	{
		
		private string _SoPhieu;
		
		private string _MaMH;
		
		private string _NoiDung;
		
		private System.Nullable<decimal> _DonGia;
		
		public sp_ChiTietPhieuThuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					this._MaMH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(100)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
	}
	
	public partial class sp_GetSinhVienResult
	{
		
		private string _Mssv;
		
		private string _Hoten;
		
		private string _Gioitinh;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Lophoc;
		
		private string _Mail;
		
		private string _MatKhau;
		
		public sp_GetSinhVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mssv", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Mssv
		{
			get
			{
				return this._Mssv;
			}
			set
			{
				if ((this._Mssv != value))
				{
					this._Mssv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(30)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(10)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this._Gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this._Ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lophoc", DbType="VarChar(10)")]
		public string Lophoc
		{
			get
			{
				return this._Lophoc;
			}
			set
			{
				if ((this._Lophoc != value))
				{
					this._Lophoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(100)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
